# setup a postgres database and litellm
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  litellm:
    image: "docker.io/library/${DKR_IMAGE_TAG}"
    container_name: litellm
    env_file:
      - .env
    ports:
      - "4000:4000"
    depends_on:
      - postgres
volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      device: ./postgresql/data
      o: bind